[user]
	name = Adam Bozson
	email = adam@bozson.io
[credential]
	helper = osxkeychain
[core]
	editor = vim
[commit]
	gpgsign = true
[filter "lfs"]
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
[pull]
	rebase = false
[bash]
	showInformativeStatus = false
	showDirtyState = true
	showUntrackedFiles = true
[init]
	defaultBranch = main
[push]
    autoSetupRemote = true
