" Use syntax highlighting
syntax on

" Set tabs to enter 4 spaces as the default indent
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" Follow the current indentation 
set smartindent

" Allow mouse to move cursor
set mouse=a

" More powerful backspace
set backspace=indent,eol,start

